name: Conser

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Kutuphaneleri Yukle
        run: pip install -r requirements.txt
      - name: Botu Calistir
        run: python takip.py
